# Autogenerated wrapper script for JonkerVolgenant_jll for x86_64-w64-mingw32
export libJonkerVolgenant

JLLWrappers.@generate_wrapper_header("JonkerVolgenant")
JLLWrappers.@declare_library_product(libJonkerVolgenant, "libJonkerVolgenant.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libJonkerVolgenant,
        "bin\\libJonkerVolgenant.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
